+ find the golang download url generically
  - try to check the following download locations in order

      1. http://golang.org/dl
      2. http://go.googlecode.com/files

    Otherwise, bail out with an error message.

diff --git a/libexec/goenv-install b/libexec/goenv-install
--- a/libexec/goenv-install
+++ b/libexec/goenv-install
@@ -8,6 +8,45 @@
 # Bomb out if we hit an error, ever
 set -e
 
+# helper functions
+function warn() {
+    printf '\033[0;31m%s\033[0m\n' "$1" >&2
+}
+
+function die() {
+    warn "$1"
+    exit 1
+}
+
+function download_url_exist() {
+    local url="$1"
+    curl -L --output /dev/null --silent --head --fail "$url"
+}
+
+function download_url() {
+    local version="$1"
+    local platform="$2"
+    local arch="$3"
+    local extra="$4"
+
+    # newer versions are at http://golang.org/dl
+    # older versions are at http://go.googlecode.com/files
+
+    local base_urls=("http://golang.org/dl" "http://go.googlecode.com/files")
+    local download=""
+
+    for base_url in "${base_urls[@]}"
+    do
+        download="${base_url}/go${version}.${platform}-${arch}${extra}.tar.gz"
+        if download_url_exist $download ;
+        then
+            echo $download
+            return
+        fi
+    done
+    die "[err] Couldn't find download url for golang version '$version'"
+}
+
 # Verbose output in debug mode
 [ -n "$GOENV_DEBUG" ] && {
   set -x
@@ -44,12 +83,7 @@ if [ "$platform" = "darwin" ]; then
 fi
 
 # URL to download from
-if [ "$version" = "1.3" -o "$version" \> "1.3" ]; then
-    base_url="http://golang.org/dl"
-else
-    base_url="https://go.googlecode.com/files"
-fi
-download="${base_url}/go${version}.${platform}-${arch}${extra}.tar.gz"
+download=$(download_url $version $platform $arch $extra)
 
 # Can't get too clever here
 set +e
